"""Versioned runtime contracts for the OpBench v0.6 evaluation platform."""

from op_bench.runtime.canonical import canonical_json, canonical_sha256
from op_bench.runtime.conformance import (
    CONFORMANCE_IGNORED_FIELDS_V1,
    ConformanceComparison,
    ConformanceEntry,
    ConformanceRunReport,
    ConformanceSnapshot,
    RuntimeConformanceRunner,
    compare_conformance_snapshots,
    normalize_conformance_snapshot,
)
from op_bench.runtime.actions import (
    CanonicalActionService,
    CommandExecution,
    RegisteredTest,
)
from op_bench.runtime.adapters import (
    AdapterActionChannel,
    AdapterActionClient,
    AdapterContext,
    CanonicalAgentAdapter,
    ScriptedAdapterResult,
    ScriptedCanonicalAdapter,
)
from op_bench.runtime.codex_adapter import (
    CODEX_ADAPTER_STATUSES,
    CodexAdapterResult,
    CodexCanonicalAdapter,
    subprocess_command_runner,
)
from op_bench.runtime.artifacts import ArtifactReference, PublicArtifactStore
from op_bench.runtime.backends import (
    DockerRuntimeBackend,
    LocalProcessBackend,
    RemoteDockerRuntimeBackend,
    RuntimeAttemptContext,
    RuntimeBackend,
    RuntimeBackendUnavailable,
    RuntimeCleanupResult,
    RuntimeCommandBackend,
    RuntimeCommandResult,
    RuntimeEvidence,
    RuntimeTargetBinding,
    ScriptedRuntimeBackend,
    load_runtime_target_binding,
)
from op_bench.runtime.events import EventJournal, verify_action_pairing, verify_event_chain
from op_bench.runtime.evaluation import (
    AttemptEvaluationCoordinator,
    CompletedEvaluation,
    EvaluationInfrastructureError,
    FreshEvaluationBackend,
    FreshEvaluator,
    PrivateEvaluationEvidence,
    ReplayEvaluationEvidence,
    SelectorExecution,
    StrictPatchApplyError,
)
from op_bench.runtime.local_evaluation import (
    EvaluationOnlyTestAsset,
    LocalGitEvaluationBackend,
    LocalGitSource,
    git_archive_source_identity,
    structured_unittest_summary,
)
from op_bench.runtime.runtime_evaluation import RuntimeFreshEvaluationBackend
from op_bench.runtime.replay import (
    LEGACY_ROOTS,
    ReplayCase,
    ReplayDifference,
    ReplayResult,
    ReplayRunReport,
    ReplayRunner,
    ReplaySummary,
    build_replay_inventory,
)
from op_bench.runtime.profiles import (
    RuntimeProfileRegistry,
    load_runtime_profile_registry,
)
from op_bench.runtime.process_actions import ProcessActionExchange
from op_bench.runtime.orchestrator import (
    V1_ADAPTER_IDS,
    V06Orchestrator,
    V06RunRequest,
    V06RunResult,
)
from op_bench.runtime.resources import (
    AttemptResourceLedger,
    RuntimeCleanupEntry,
    RuntimeCleanupReport,
    RuntimeLease,
    RuntimeLeaseStore,
    RuntimeResourceHandle,
    RuntimeResourceRecord,
    parse_runtime_lease_store,
    parse_runtime_resource_ledger,
    runtime_raw_handle_hash,
    runtime_resource_id,
    runtime_resource_record_hash,
    verify_runtime_cleanup,
    verify_runtime_resource_evidence,
    verify_runtime_resource_ownership,
)
from op_bench.runtime.integrity import (
    load_run_manifest_artifact,
    persist_integrity_reports,
    selected_attempts_from_ledger,
    verify_run_artifacts,
)
from op_bench.runtime.session import (
    AttemptSession,
    SessionStateError,
    TerminationAttribution,
    termination_attribution,
)
from op_bench.runtime.summary import (
    SelectedAttempt,
    rebuild_results,
    rebuild_summary,
    result_record,
    write_rebuilt_outputs,
)
from op_bench.runtime.resume import (
    AttemptLedger,
    AttemptLedgerRecord,
    ResumeDecision,
    parse_attempt_ledger,
)
from op_bench.runtime.run_artifacts import (
    AttemptArtifactIndex,
    AttemptArtifactStore,
    EvaluationArtifactHashes,
    retry_directory_name,
)
from op_bench.runtime.task_view import (
    AgentLaunchInput,
    TaskViewPolicy,
    agent_task_view_identity,
    assert_public_artifact_safe,
    project_agent_task_view,
)
from op_bench.runtime.validation import ContractError
from op_bench.runtime.workspace import (
    AuthoritativeWorkspace,
    FrozenPatch,
    PatchArtifact,
    WorkspacePolicy,
    assert_patch_identity_handoff,
    build_patch_artifact,
)

__all__ = [
    "AgentLaunchInput",
    "AttemptArtifactIndex",
    "AttemptArtifactStore",
    "AttemptEvaluationCoordinator",
    "AttemptLedger",
    "AttemptLedgerRecord",
    "AttemptResourceLedger",
    "AttemptSession",
    "ArtifactReference",
    "AdapterActionChannel",
    "AdapterActionClient",
    "AdapterContext",
    "AuthoritativeWorkspace",
    "CanonicalActionService",
    "CanonicalAgentAdapter",
    "ScriptedAdapterResult",
    "ScriptedCanonicalAdapter",
    "CODEX_ADAPTER_STATUSES",
    "CodexAdapterResult",
    "CodexCanonicalAdapter",
    "CONFORMANCE_IGNORED_FIELDS_V1",
    "CommandExecution",
    "ContractError",
    "CompletedEvaluation",
    "ConformanceComparison",
    "ConformanceEntry",
    "ConformanceRunReport",
    "ConformanceSnapshot",
    "DockerRuntimeBackend",
    "EvaluationInfrastructureError",
    "EvaluationArtifactHashes",
    "EvaluationOnlyTestAsset",
    "EventJournal",
    "FreshEvaluationBackend",
    "FreshEvaluator",
    "FrozenPatch",
    "PatchArtifact",
    "persist_integrity_reports",
    "PrivateEvaluationEvidence",
    "ProcessActionExchange",
    "V1_ADAPTER_IDS",
    "V06Orchestrator",
    "V06RunRequest",
    "V06RunResult",
    "PublicArtifactStore",
    "RegisteredTest",
    "RuntimeProfileRegistry",
    "RemoteDockerRuntimeBackend",
    "RuntimeAttemptContext",
    "RuntimeBackend",
    "RuntimeBackendUnavailable",
    "RuntimeCleanupEntry",
    "RuntimeCleanupReport",
    "RuntimeCleanupResult",
    "RuntimeCommandBackend",
    "RuntimeCommandResult",
    "RuntimeConformanceRunner",
    "RuntimeEvidence",
    "RuntimeFreshEvaluationBackend",
    "RuntimeLease",
    "RuntimeLeaseStore",
    "RuntimeResourceHandle",
    "RuntimeResourceRecord",
    "RuntimeTargetBinding",
    "load_runtime_target_binding",
    "ScriptedRuntimeBackend",
    "ResumeDecision",
    "SessionStateError",
    "SelectorExecution",
    "SelectedAttempt",
    "StrictPatchApplyError",
    "TaskViewPolicy",
    "TerminationAttribution",
    "WorkspacePolicy",
    "LocalGitEvaluationBackend",
    "LocalGitSource",
    "LocalProcessBackend",
    "LEGACY_ROOTS",
    "ReplayCase",
    "ReplayDifference",
    "ReplayEvaluationEvidence",
    "ReplayResult",
    "ReplayRunReport",
    "ReplayRunner",
    "ReplaySummary",
    "agent_task_view_identity",
    "assert_patch_identity_handoff",
    "assert_public_artifact_safe",
    "build_patch_artifact",
    "build_replay_inventory",
    "canonical_json",
    "canonical_sha256",
    "compare_conformance_snapshots",
    "git_archive_source_identity",
    "load_runtime_profile_registry",
    "load_run_manifest_artifact",
    "parse_runtime_lease_store",
    "parse_runtime_resource_ledger",
    "normalize_conformance_snapshot",
    "runtime_raw_handle_hash",
    "runtime_resource_id",
    "runtime_resource_record_hash",
    "structured_unittest_summary",
    "subprocess_command_runner",
    "project_agent_task_view",
    "parse_attempt_ledger",
    "rebuild_results",
    "rebuild_summary",
    "retry_directory_name",
    "result_record",
    "selected_attempts_from_ledger",
    "termination_attribution",
    "verify_action_pairing",
    "verify_event_chain",
    "verify_run_artifacts",
    "verify_runtime_cleanup",
    "verify_runtime_resource_evidence",
    "verify_runtime_resource_ownership",
    "write_rebuilt_outputs",
]
